export const procurementData = [
  {
    orderInfo: {
      invoiceName: "M23456145",
      date: "2024 Sep 04 at 09:44 AM",
      amount: "214,124 €",
      orderType: "Installation of Fiber Optics",
      quantity: 1,
      weight: "650g",
      cost: "214,124 €",
    },
    shippingInfo: {
      address: "Elisabeth-Selbert-Straße 2, 80398",
      deliveryDate: "2024 Sep 27 at 09:44 AM",
      customerName: "Thomas",
      contact: "(+49) 163 555 1584",
      mailId: "prteam@telekom.de",
      paymentStatus: "Done",
      paymentStatusColor: "text-green-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456146",
      date: "2024 Sep 05 at 10:00 AM",
      amount: "150,500 €",
      orderType: "Installation of Fiber Optics",
      quantity: 2,
      weight: "1kg",
      cost: "150,500 €",
    },
    shippingInfo: {
      address: "Sample Address 1",
      deliveryDate: "2024 Sep 28 at 10:00 AM",
      customerName: "Customer 1",
      contact: "(+49) 163 555 1111",
      mailId: "customer1@example.com",
      paymentStatus: "Pending",
      paymentStatusColor: "text-yellow-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456147",
      date: "2024 Sep 06 at 11:00 AM",
      amount: "300,000 €",
      orderType: "Installation of Fiber Optics",
      quantity: 3,
      weight: "1.5kg",
      cost: "300,000 €",
    },
    shippingInfo: {
      address: "Sample Address 2",
      deliveryDate: "2024 Sep 29 at 11:00 AM",
      customerName: "Customer 2",
      contact: "(+49) 163 555 2222",
      mailId: "customer2@example.com",
      paymentStatus: "In Progress",
      paymentStatusColor: "text-blue-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456148",
      date: "2024 Sep 07 at 12:00 PM",
      amount: "180,000 €",
      orderType: "Installation of Fiber Optics",
      quantity: 1,
      weight: "800g",
      cost: "180,000 €",
    },
    shippingInfo: {
      address: "Sample Address 3",
      deliveryDate: "2024 Sep 30 at 12:00 PM",
      customerName: "Customer 3",
      contact: "(+49) 163 555 3333",
      mailId: "customer3@example.com",
      paymentStatus: "Done",
      paymentStatusColor: "text-green-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456149",
      date: "2024 Sep 08 at 01:00 PM",
      amount: "220,000 €",
      orderType: "Installation of Fiber Optics",
      quantity: 2,
      weight: "1.2kg",
      cost: "220,000 €",
    },
    shippingInfo: {
      address: "Sample Address 4",
      deliveryDate: "2024 Oct 01 at 01:00 PM",
      customerName: "Customer 4",
      contact: "(+49) 163 555 4444",
      mailId: "customer4@example.com",
      paymentStatus: "Pending",
      paymentStatusColor: "text-yellow-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456150",
      date: "2024 Sep 09 at 02:00 PM",
      amount: "90,000 €",
      orderType: "Installation of Fiber Optics",
      quantity: 1,
      weight: "500g",
      cost: "90,000 €",
    },
    shippingInfo: {
      address: "Sample Address 5",
      deliveryDate: "2024 Oct 02 at 02:00 PM",
      customerName: "Customer 5",
      contact: "(+49) 163 555 5555",
      mailId: "customer5@example.com",
      paymentStatus: "Done",
      paymentStatusColor: "text-green-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456151",
      date: "2024 Sep 10 at 03:00 PM",
      amount: "275,000 €",
      orderType: "Installation of Fiber Optics",
      quantity: 2,
      weight: "1.1kg",
      cost: "275,000 €",
    },
    shippingInfo: {
      address: "Sample Address 6",
      deliveryDate: "2024 Oct 03 at 03:00 PM",
      customerName: "Customer 6",
      contact: "(+49) 163 555 6666",
      mailId: "customer6@example.com",
      paymentStatus: "Pending",
      paymentStatusColor: "text-yellow-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
  {
    orderInfo: {
      invoiceName: "M23456152",
      date: "2024 Sep 11 at 04:00 PM",
      amount: "350,000 €",
      orderType: "Installation of Fiber Optics",
      quantity: 3,
      weight: "1.8kg",
      cost: "350,000 €",
    },
    shippingInfo: {
      address: "Sample Address 7",
      deliveryDate: "2024 Oct 04 at 04:00 PM",
      customerName: "Customer 7",
      contact: "(+49) 163 555 7777",
      mailId: "customer7@example.com",
      paymentStatus: "Done",
      paymentStatusColor: "text-green-500",
    },
    labels: {
      order: ["Order ID", "Order Type", "Quantity", "Weight", "Cost"],
      shipping: [
        "Ship To",
        "Customer Name",
        "Contact",
        "Mail ID",
        "Payment Status",
      ],
    },
  },
];
